// Mocks generated by Mockito 5.0.14 from annotations
// in pokedex/test/features/pokemon/domain/usecases/get_pokemon_detail_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pokedex/src/core/params/search_params.dart' as _i7;
import 'package:pokedex/src/core/resources/data_state.dart' as _i2;
import 'package:pokedex/src/features/pokemon/domain/entities/detail/pokemon.dart'
    as _i6;
import 'package:pokedex/src/features/pokemon/domain/entities/list/pokemon_list.dart'
    as _i5;
import 'package:pokedex/src/features/pokemon/domain/repositories/pokemon_repository.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeDataState_0<T> extends _i1.Fake implements _i2.DataState<T> {}

/// A class which mocks [PokemonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRepository extends _i1.Mock implements _i3.PokemonRepository {
  MockPokemonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<_i5.PokemonList>> getPokemonList({int? page}) =>
      (super.noSuchMethod(Invocation.method(#getPokemonList, [], {#page: page}),
              returnValue: Future<_i2.DataState<_i5.PokemonList>>.value(
                  _FakeDataState_0<_i5.PokemonList>()))
          as _i4.Future<_i2.DataState<_i5.PokemonList>>);
  @override
  _i4.Future<_i2.DataState<_i6.PokemonDetail>> getPokemon({int? id}) =>
      (super.noSuchMethod(Invocation.method(#getPokemon, [], {#id: id}),
              returnValue: Future<_i2.DataState<_i6.PokemonDetail>>.value(
                  _FakeDataState_0<_i6.PokemonDetail>()))
          as _i4.Future<_i2.DataState<_i6.PokemonDetail>>);
  @override
  _i4.Future<_i2.DataState<_i5.PokemonList>> searchPokemonByName(
          {_i7.SearchParams? params}) =>
      (super.noSuchMethod(
              Invocation.method(#searchPokemonByName, [], {#params: params}),
              returnValue: Future<_i2.DataState<_i5.PokemonList>>.value(
                  _FakeDataState_0<_i5.PokemonList>()))
          as _i4.Future<_i2.DataState<_i5.PokemonList>>);
  @override
  String toString() => super.toString();
}
